//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEI.TrainingSimulator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FEI.TrainingSimulator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akceptovať.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba pri pridávaní príkladu.
        /// </summary>
        internal static string AddTaskError {
            get {
                return ResourceManager.GetString("AddTaskError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Príklad bol úspešne pridaný..
        /// </summary>
        internal static string AddTaskTitle {
            get {
                return ResourceManager.GetString("AddTaskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automat používa neplatný alebo nepovolený symbol &apos;{0}&apos;..
        /// </summary>
        internal static string AutomatonInvalidSymbol {
            get {
                return ResourceManager.GetString("AutomatonInvalidSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automat nie je správny. Líši sa na slove &apos;{0}&apos;.
        ///Očakávané: {1}.
        ///Študentov automat: {2}..
        /// </summary>
        internal static string AutomatonMismatchError {
            get {
                return ResourceManager.GetString("AutomatonMismatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automat nemá žiadny koncový stav..
        /// </summary>
        internal static string AutomatonNoFinalState {
            get {
                return ResourceManager.GetString("AutomatonNoFinalState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automat nemá začiatočný stav..
        /// </summary>
        internal static string AutomatonNoStartState {
            get {
                return ResourceManager.GetString("AutomatonNoStartState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automat neobsahuje žiadne stavy..
        /// </summary>
        internal static string AutomatonNoStates {
            get {
                return ResourceManager.GetString("AutomatonNoStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automat nie je deterministický. Zo stavu &apos;{0}&apos; existuje viac prechodov pre symbol &apos;{1}&apos;..
        /// </summary>
        internal static string AutomatonNotDeterministic {
            get {
                return ResourceManager.GetString("AutomatonNotDeterministic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Začať.
        /// </summary>
        internal static string Begin {
            get {
                return ResourceManager.GetString("Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riešenie je správne.
        /// </summary>
        internal static string Correct {
            get {
                return ResourceManager.GetString("Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtiažnosť.
        /// </summary>
        internal static string Difficulty {
            get {
                return ResourceManager.GetString("Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ľahká.
        /// </summary>
        internal static string Easy {
            get {
                return ResourceManager.GetString("Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konečný stroj.
        /// </summary>
        internal static string FinalAutomaton {
            get {
                return ResourceManager.GetString("FinalAutomaton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formálna špecifikácia.
        /// </summary>
        internal static string FormalSpecification {
            get {
                return ResourceManager.GetString("FormalSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tažká.
        /// </summary>
        internal static string Hard {
            get {
                return ResourceManager.GetString("Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to počiatočný stav.
        /// </summary>
        internal static string InitialState {
            get {
                return ResourceManager.GetString("InitialState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neplatná očakávaná hodnota pri slove &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidExpectedValue {
            get {
                return ResourceManager.GetString("InvalidExpectedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepodarilo sa načítať vybranú sadu príkladov..
        /// </summary>
        internal static string LoadErrorTaskSet {
            get {
                return ResourceManager.GetString("LoadErrorTaskSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stredná.
        /// </summary>
        internal static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadanie neobsahuje referenčný model.
        ///Kontaktujte tvoru úlohy - Vášho prednášajúceho alebo cvičiaceho..
        /// </summary>
        internal static string MissingReferenceModel {
            get {
                return ResourceManager.GetString("MissingReferenceModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neboli nájdené žiadne testovacie prípady..
        /// </summary>
        internal static string NoTestCasesFound {
            get {
                return ResourceManager.GetString("NoTestCasesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zásobníkový automat.
        /// </summary>
        internal static string PushdownAutomaton {
            get {
                return ResourceManager.GetString("PushdownAutomaton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Náhodný príkad.
        /// </summary>
        internal static string RandomTask {
            get {
                return ResourceManager.GetString("RandomTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navrhnite deterministický konečný automat, príp. jeho stavový diagram, ktorý rozpoznáva jazyk $L_A$.
        /// </summary>
        internal static string RandomTaskSpecMedium {
            get {
                return ResourceManager.GetString("RandomTaskSpecMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referenčný automat.
        /// </summary>
        internal static string ReferenceAutomaton {
            get {
                return ResourceManager.GetString("ReferenceAutomaton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referenčný model obsahuje syntaktické chyby.
        ///Kontaktujte tvoru úlohy - Vášho prednášajúceho alebo cvičiaceho..
        /// </summary>
        internal static string ReferenceModelSyntaxError {
            get {
                return ResourceManager.GetString("ReferenceModelSyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regex neobsahuje žiadne symboly abecedy..
        /// </summary>
        internal static string RegexNoAlphabetSymbols {
            get {
                return ResourceManager.GetString("RegexNoAlphabetSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regex obsahuje neuzavretú množinu []..
        /// </summary>
        internal static string RegexUnclosedSet {
            get {
                return ResourceManager.GetString("RegexUnclosedSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odmietnuť.
        /// </summary>
        internal static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap small_open {
            get {
                object obj = ResourceManager.GetObject("small_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to symbol na dne zásobníka.
        /// </summary>
        internal static string StackIntialSymbol {
            get {
                return ResourceManager.GetString("StackIntialSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Váš model obsahuje syntaktické chyby..
        /// </summary>
        internal static string StudentModelSynatxError {
            get {
                return ResourceManager.GetString("StudentModelSynatxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pridanie príkladu.
        /// </summary>
        internal static string TaskAddedMessage {
            get {
                return ResourceManager.GetString("TaskAddedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtiažnosť zadania:.
        /// </summary>
        internal static string TaskDifficulty {
            get {
                return ResourceManager.GetString("TaskDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametre zadania.
        /// </summary>
        internal static string TaskParameters {
            get {
                return ResourceManager.GetString("TaskParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Vybraný súbor sa nenachádza v priečinku príkladov.
        ///
        ///Chcete ho skopírovať do priečinka príkladov a používať odtiaľ?
        ///    .
        /// </summary>
        internal static string TaskSetCopyFile {
            get {
                return ResourceManager.GetString("TaskSetCopyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Špecifikácia zadania.
        /// </summary>
        internal static string TaskSpecification {
            get {
                return ResourceManager.GetString("TaskSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ zadania:.
        /// </summary>
        internal static string TaskType {
            get {
                return ResourceManager.GetString("TaskType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sada testov.
        /// </summary>
        internal static string TestCases {
            get {
                return ResourceManager.GetString("TestCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sada príkladov.
        /// </summary>
        internal static string TestSet {
            get {
                return ResourceManager.GetString("TestSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax:
        ///c1#symbol + c2#symbol + ... = kn + q
        ///
        ///Príklad:
        ///1#a+1#b=2n+0.
        /// </summary>
        internal static string ToolTipFormula {
            get {
                return ResourceManager.GetString("ToolTipFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podporované modely:
        ///.fa  - konečný automat
        ///.pa  - zásobníkový automat
        ///.tm  - Turingov stroj
        ///
        ///Referenčný model musí byť rovnaký, ako model úlohy!.
        /// </summary>
        internal static string ToolTipReference {
            get {
                return ResourceManager.GetString("ToolTipReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podporované:
        ///*  - opakovanie
        ///|  - alternatíva
        ///() - zoskupenie
        ///[] - množina symbolov
        ///
        ///Príklady:
        ///a*b
        ///(a|b)*abb
        ///[0-9]+
        ///(a|b)*abba(a|b)*.
        /// </summary>
        internal static string ToolTipRegex {
            get {
                return ResourceManager.GetString("ToolTipRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na zápis špecifikácie je možné použiť matematické výrazy. Zapisujú sa v MathJax syntaxi, podobnej LaTeXu.
        ///
        ///Podporované sú bežné matematické konštrukcie:
        ///- horné a dolné indexy
        ///- grécke symboly
        ///- množiny
        ///- matematické relácie a operátory
        ///- blokové výrazy pomocou $$ ... $$.
        /// </summary>
        internal static string ToolTipSpecification {
            get {
                return ResourceManager.GetString("ToolTipSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manuálne testovacie prípady pre overovanie riešenia.
        ///
        ///Každé slovo je možné označiť ako:
        ///- Akceptovať
        ///- Odmietnuť
        ///
        ///Tieto testy budú použité počas kontroly riešenia.
        ///Prázdne slovo je možné zadať ako ε alebo jednu medzeru..
        /// </summary>
        internal static string ToolTipTestCases {
            get {
                return ResourceManager.GetString("ToolTipTestCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manuálne testovacie slová pre overovanie riešenia.
        ///
        ///Tieto testy budú použité počas kontroly riešenia.
        ///Prázdne slovo je možné zadať ako ε alebo jednu medzeru..
        /// </summary>
        internal static string ToolTipTestWords {
            get {
                return ResourceManager.GetString("ToolTipTestWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Trainer {
            get {
                object obj = ResourceManager.GetObject("Trainer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trenažér ( {0} ).
        /// </summary>
        internal static string TrainerWindowText {
            get {
                return ResourceManager.GetString("TrainerWindowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prechodová funkcia.
        /// </summary>
        internal static string TransitionFunction {
            get {
                return ResourceManager.GetString("TransitionFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riešenie obsahuje syntaktické chyby v prechodových funkciách..
        /// </summary>
        internal static string TransitionSyntaxError {
            get {
                return ResourceManager.GetString("TransitionSyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Turing {
            get {
                object obj = ResourceManager.GetObject("Turing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turingov stroj.
        /// </summary>
        internal static string TuringMachine {
            get {
                return ResourceManager.GetString("TuringMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neznámy režim: {0}.
        ///Kontaktujte tvoru úlohy - Vášho prednášajúceho alebo cvičiaceho..
        /// </summary>
        internal static string UnknownModeError {
            get {
                return ResourceManager.GetString("UnknownModeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap validated {
            get {
                object obj = ResourceManager.GetObject("validated", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte typ automatu..
        /// </summary>
        internal static string ValidationErrorModelType {
            get {
                return ResourceManager.GetString("ValidationErrorModelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hĺbka rekurzie má nesprávny formát alebo je prázdne..
        /// </summary>
        internal static string ValidationErrorRecursionDepth {
            get {
                return ResourceManager.GetString("ValidationErrorRecursionDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte obtiažnosť príkladu..
        /// </summary>
        internal static string ValidationErrorTaskDifficulty {
            get {
                return ResourceManager.GetString("ValidationErrorTaskDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model referenčného riešenia sa nezhoduje s modelom zadania..
        /// </summary>
        internal static string ValidationErrorTaskModelMismatchWithReference {
            get {
                return ResourceManager.GetString("ValidationErrorTaskModelMismatchWithReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadajte názov príkladu..
        /// </summary>
        internal static string ValidationErrorTaskName {
            get {
                return ResourceManager.GetString("ValidationErrorTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte alebo zadajte cestu k sade príkladov..
        /// </summary>
        internal static string ValidationErrorTaskSetPath {
            get {
                return ResourceManager.GetString("ValidationErrorTaskSetPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadajte popis zadania..
        /// </summary>
        internal static string ValidationErrorTaskSpecification {
            get {
                return ResourceManager.GetString("ValidationErrorTaskSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte spôsob overovania..
        /// </summary>
        internal static string ValidationErrorTaskValidationMethod {
            get {
                return ResourceManager.GetString("ValidationErrorTaskValidationMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadajte hodnotu pre overovanie príkladu..
        /// </summary>
        internal static string ValidationErrorVerfication {
            get {
                return ResourceManager.GetString("ValidationErrorVerfication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pridajte aspoň jeden testovací prípad..
        /// </summary>
        internal static string ValidationErrorZeroTaskTest {
            get {
                return ResourceManager.GetString("ValidationErrorZeroTaskTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML súbor nemá koreňový element &lt;tasks&gt;..
        /// </summary>
        internal static string XmlMissingRootTask {
            get {
                return ResourceManager.GetString("XmlMissingRootTask", resourceCulture);
            }
        }
    }
}
